# Generated by Django 4.2.7 on 2023-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_book_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.CharField(max_length=30)),
                ('Year', models.PositiveIntegerField()),
                ('Genre', models.CharField(max_length=30)),
            ],
        ),
    ]
